services:
  postgres:
    image: postgres:15
    container_name: nomina_postgres
    environment:
      POSTGRES_DB: numadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: numanomina2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d numadb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  mongodb:
    image: mongo:6
    container_name: nomina_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: nomina_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: nomina_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: numa-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data: