# Puerto
server.port=8080

# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/numadb
spring.datasource.username=postgres
spring.datasource.password=numanomina2025
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MongoDB Local
spring.data.mongodb.uri=mongodb://localhost:27017/numa_mongo
spring.data.mongodb.database=numa_mongo
# Logs
logging.level.com.nomina.numa=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs