server.port=8080
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/numadb
spring.datasource.username=postgres
spring.datasource.password=numanomina2025
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.mongodb.uri=mongodb://mongodb:27017/numa_mongo
spring.data.redis.host=redis
spring.data.redis.port=6379
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
logging.level.com.nomina.numa=DEBUG
logging.level.org.springframework.security=DEBUG
spring.web.cors.allowed-origins=http://localhost:4200
